-- EXERCICIO 1
SELECT COUNT(P.IDSTATUS) AS QUANTIDADE, S.DSSTATUS 
  FROM TB_PROCESSO P
  	   INNER JOIN TB_STATUS S ON P.IDSTATUS = S.IDSTATUS
 GROUP BY S.IDSTATUS, S.DSSTATUS  
 
-- EXERCICIO 2
SELECT P.NROPROCESSO, X.DTANDAMENTO 
  FROM TB_PROCESSO P 
  	   INNER JOIN 
  	   			(
  	   				SELECT IDPROCESSO, MAX(DTANDAMENTO) AS DTANDAMENTO
					  FROM TB_ANDAMENTO
					 GROUP BY IDPROCESSO
  	   			) AS X ON P.IDPROCESSO = X.IDPROCESSO
WHERE YEAR(P.DTENCERRAMENTO) = 2013 


-- EXERCICIO 3
SELECT COUNT(DTENCERRAMENTO) AS QUANTIDADE, DTENCERRAMENTO
  FROM TB_PROCESSO
GROUP BY DTENCERRAMENTO
HAVING COUNT(DTENCERRAMENTO) > 5

-- EXERCICIO 4
SELECT  REPLICATE('0',(12 - LEN(CAST(NROPROCESSO AS VARCHAR)))) 
		+ CAST(NROPROCESSO AS VARCHAR) AS NROPROCESSO
  FROM TB_PROCESSO
